name: Unit Test
on: [push, workflow_dispatch]
jobs:
# job responsible for running Flutter tests on Android devices
  android:
    runs-on: macos-11
    strategy:
      matrix:
        api-level:
          - 29
          # you can add more API level if you want to run your tests on different API
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.6'
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11"
      - name: Install Flutter dependencies
        run: flutter pub get 
      - name: Run integration tests login test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test test/auth/view/Login_test.dart
      # - name: Run integration tests add photo test
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: ${{ matrix.api-level }}
      #     arch: x86_64
      #     profile: Nexus 6
      #     script: flutter test integration_test/add_album_test.dart --verbose
