name: main
on: [push, workflow_dispatch]
jobs:
# job responsible for running Flutter tests on Android devices
  android:
    runs-on: macos-11
    strategy:
      matrix:
        api-level:
          - 29
          # you can add more API level if you want to run your tests on different API
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # instead of "channel: stable", you could be more precise by specifying the exact version of Flutter you're using:
          # flutter-version: '<FLUTTER_VERSION>'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests login test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test/app_test.dart --verbose
      - name: Run integration tests add photo test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test/add_album_test.dart --verbose
